# Generated by Django 3.0.7 on 2020-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date', models.DateField(verbose_name='Дата выполнения')),
                ('done', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
