# Generated by Django 3.0.7 on 2020-06-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200630_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
