# Generated by Django 3.0.7 on 2020-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200630_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
